### ISSUE TITLE
SCSS discourages @import in favor of @use rule

### ISSUE THREAD

**Issue by arrontp** [KittyGiraudel/sass-boilerplate#41]
SASS/SCSS are discouraging and phasing out support for `@import` rule in favor of the `@use` rule.

This makes styling more readable, safer and reduces compile time.

For more detail see '⚠**Heads Up!**' notice in the [documentation here](https://sass-lang.com/documentation/at-rules/import).

Read [`@use` rule docs here](https://sass-lang.com/documentation/at-rules/use).

Would it be worth updating `main.scss` in response to this?

**Comment by atpriyanshu** [comment]
@arrontp , you are right. You should `create a new branch`, fix `@import` to `@use` and open `the new pull request`.
Can I do it for you?

**Comment by yanyiik99** [comment]
hi bro I don't understant what do you mean put the vendor in folder /vendor-extensions/_bootstrap.sass
