### ISSUE TITLE
$breakpoint

### ISSUE THREAD

**Issue by mrnonchalantz** [KittyGiraudel/sass-boilerplate#42]
Hi, how to use $breakpoint , i tried these both it seem didnt work? Thanks

is it 

`@include media("small") {
  .box {
    width: 350px;
  }
}`

or 

`.box {
     width: 500px;
     @include media("small") {
          width: 350px; 
     }
}`

**Comment by KittyGiraudel** [comment]
I had to have a look, but it appears that in this boilerplate, `$breakpoints` is just a map of breakpoints for convenience. I’m not sure what your `media` mixin is, but it doesn’t seem to be part of this boilerplate?

**Comment by kambanwait** [comment]
Looks like you need to create a mixin to handle the breakpoints and your media-queries

e.g: 

```
# Breakpoints is set already, leave as it is.
$breakpoints: (
  'small': 320px,
  'medium': 768px,
  'large': 1024px,
) !default;


# Mixin needed to make use of defined breakpoints.
@mixin respond-to($bp) {
  // use Sass map-get to retrieve the value you've passed in to the mixin
  $value: map-get($breakpoints, $bp);

  // if the BP exists then we print out the media query with the value
  @if $value != null {
    @media (min-width: $value) {
      @content;
    }
  }
   // if the BP doesn't exist then we return a warning
  @else {
    @warn "No value assigned to `#{$bp}` in `$breakpoints`";
  }
}

```

**Comment by KittyGiraudel** [comment]
You could also use [include-media](https://eduardoboucas.github.io/include-media/). :)

**Comment by mrnonchalantz** [comment]
Thanks @kambanwait and @KittyGiraudel 

I think, I will use [include-media](https://eduardoboucas.github.io/include-media/)

**Comment by mrnonchalantz** [comment]
i tried using `@include media ("<=phone) {//css do stuff}` but it throw me error : no mixin named media

**Comment by KittyGiraudel** [comment]
You need to make sure the `media` mixin (defined by the library) is imported before your code so it’s available.
