### ISSUE TITLE
layout vs layouts

### ISSUE THREAD

**Issue by azzamsa** [KittyGiraudel/sass-boilerplate#52]
Hi, 👋

What is the reason behind the "layout" naming. Why it is not "layouts"?

Thank you 🍨

**Comment by KittyGiraudel** [comment]
Honestly I can’t remember the exact reason. I _think_ it’s because one would typically put things like the header, footer, and other layout structures, in there. Hence singular “layout”, as in “for the layout”. But feel free to rename it in your projects if it makes more sense to you. :)

**Comment by azzamsa** [comment]
Thank you so much for this boilerplate. It help us a lot :ice_cream:
